export default {
  'zh-CN': {
    'Setting': '设置',
    'Enable': '启用',
    'Rules not found, ': '没有找到任何代理规则，',
    'Rules not found': '还没有添加任何代理规则',
    'Click to Add': '点击添加',
    'Domain/URL': '域名/URL',
    'Tags': '标签',
    'Order': '排序',
    'Note': '备注',
    'All': '全部',
    'Delete': '删除',
    'Edit': '编辑',
    'Confirm': '提示',
    'Are you sure you want to delete this rule?': '确定要删除该配置项吗？',
    'Add Rules': '添加规则',
    'Add': '添加',
    'Bulk Add': '批量添加',
    'Tags For All Rules': '统一设置标签',
    'Preview': '预览',
    'Can not get any rules, please check your input rules format': '没有解析到任何代理规则，请注意检查格式',
    'Sure to Add': '确定添加',
    'Sure to Save': '确定保存',
    'Cancel': '取消',
    'Export': '导出',
    'All Rules': '所有规则',
    'Copy and save the rules below, then you can import by the Bulk-Add next time': '将下面内容复制保存起来，下次可通过左侧的批量添加导入。',
  },
}
